### ISSUE TITLE
Can't spawn terminal or external editor

### ISSUE THREAD

**Issue by llabusch93** [flathub/com.axosoft.GitKraken#88]
Hello guys,

I can't select a terminal or external editor in the flatpak version here. When I install it usually, it does work. Any suggestions?

**Comment by Lctrs** [comment]
See #12. 

You just need to set a custom command to `flatpak-spawn --host gnome-terminal` (replace `gnome-terminal` with your own terminal bin if you're not using this one).

**Comment by llabusch93** [comment]
Thanks @Lctrs yes I just came up with that solution by myself, wrote an addition in the second you closed this. Anyway, the external editor thing is still not resolved, so this here should neither be closed.

Can you give me a solution for this as well? I used to have VS Code set.

**Comment by Lctrs** [comment]
Since you can't set a custom command for the external editor, there is no solution for editor.

I'm closing this because there is no solution on our side. Due to how flatpak works, apps inside it can't see other applications installed on the host or even other installed flatpak applications. I don't think there is a portal for this yet. So a portal would have to be created for this, and support added for it either in Flatpak or in Electron. Furthermore, since Flatpak isn't officially supported by GitKraken, don't expect a quick solution for this.

**Comment by llabusch93** [comment]
Okay too bad, thanks @Lctrs for your support and explanation!

**Comment by jkilzi** [comment]
@llabusch93 and others looking to solve this issue...
```bash
flatpak-spawn --host gnome-terminal
```
Just use this as the custom terminal command, tested on Fedora 33, cheers...

**Comment by AlejandroAkbal** [comment]
Doesnt seem to work anymore, ubuntu 22

![Image](https://github.com/user-attachments/assets/c2eca05e-f495-41d3-a5b6-75ce33404bc7)
